#! /bin/zsh
# A script to make using 256 colors in zsh less painful.
# P.C. Shyamshankar <sykora@lucentbeing.com>

typeset -Ag FX FG BG

FX=(
    reset     "[00m"
    bold      "[01m" no-bold      "[22m"
    italic    "[03m" no-italic    "[23m"
    underline "[04m" no-underline "[24m"
    blink     "[05m" no-blink     "[25m"
    reverse   "[07m" no-reverse   "[27m"
)

for color in {000..255}; do
    FG[$color]="[38;5;${color}m"
    BG[$color]="[48;5;${color}m"
done

# Add in named ansi colors
typeset -A ansi_colors
ansi_colors=(
  black   000
  red     001
  green   002
  yellow  003
  blue    004
  magenta 005
  cyan    006
  white   007
  default 008
)
for key in ${(k)ansi_colors}; do
    FG[$key]="[38;5;${ansi_colors[$key]}m"
    BG[$key]="[48;5;${ansi_colors[$key]}m"
done
